### ISSUE TITLE
Only flood images if relative change in precipitation is above a certain threshold (60%)

### ISSUE THREAD

**Issue by marpaia** [cc-ai/floods-backend#17]
For now, we are only going to apply the generative model to the image if the relative change in precipitation that is expected in 2050 is above 60%.

**Comment by Vahe987** [comment]
I don't think this is scientifically correct thing to do, we should discuss the idea and also, why 30% ?

**Comment by marpaia** [comment]
Speaking with Ata, he just let me know that we're bumping this to 60% as a result of some analysis he did regarding the relative change in precipitation levels observed after recent flooding in Quebec.

**Comment by marpaia** [comment]
Also, according to Ata, if any of the immediately adjacent grid items are above the flood threshold, flood it.

**Comment by Vahe987** [comment]
ok, cool, let's keep it 60% for now, until we get new info

**Comment by marpaia** [comment]
From a discussion with @notoraptor about how the API and UI should handle this:

<img width="758" alt="Screen Shot 2019-08-15 at 10 09 36 AM" src="https://user-images.githubusercontent.com/927168/63100319-d42e5b80-bf44-11e9-956f-9a1052651a5f.png">
