### ISSUE TITLE
Image processing error: Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Vahe987** [cc-ai/floods-backend#21]
if the address doesn't have a street view, for example "38 Galshoyan Street, Yerevan, Armenia"
 or it is a wrong address, we are getting an error
Image processing error: Error: Request failed with status code 500

also, if previous request was successful, it keeps the title and street view of the previous one. Should be empty in case of the error, to do not confuse the user
![image](https://user-images.githubusercontent.com/35110234/63049485-caeeb180-bea6-11e9-8171-99430db34f1a.png)

**Comment by marpaia** [comment]
When the address isn't supported by GSV, the API will now return a 200 OK with the following response:

```json
{
  "error": "Image not found in response from Google Street View"
}
```
