### ISSUE TITLE
Image processing error / nothing to show

### ISSUE THREAD

**Issue by melisandeteng** [cc-ai/floods-backend#29]
For some places, everything works just fine:
![working](https://user-images.githubusercontent.com/34208548/63129129-bf71b800-bf84-11e9-9da4-4b097c197a99.JPG)

Now, if I query 6666 rue saint Urbain in Montreal, the following error is returned:
![not_working](https://user-images.githubusercontent.com/34208548/63129162-dadcc300-bf84-11e9-86ec-8a63ee8a20a4.JPG)

However, if I query 6666 rue saint Urbain and it is the FIRST address I am querying when logging into th website, the error is not returned, but no image is shown:
![working_partial](https://user-images.githubusercontent.com/34208548/63129219-fea00900-bf84-11e9-98e7-95dcffa59526.JPG)

**Comment by marpaia** [comment]
This seems to be working now. I think that this was an intermittent failure due to some other issues that were going on at the time of testing. In any case, thank you for the excellent issue, @melisandeteng!!
